Gradle JVM Memory Settings to prevent Daemon crashes (JVM OutOfMemory)

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

Enable AndroidX and Jetifier

android.useAndroidX=true
android.enableJetifier=true

Disable parallel daemon workers to save RAM during compilation

org.gradle.parallel=false
org.gradle.daemon=false