STREAMING_CHUNK:Configuring JVM memory settings for Gradle...

Gradle JVM Memory Settings to prevent Daemon crashes (JVM OutOfMemory)

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

STREAMING_CHUNK:Enabling AndroidX and Jetifier flags...

Enable AndroidX and Jetifier

android.useAndroidX=true
android.enableJetifier=true

STREAMING_CHUNK:Disabling parallel workers to reduce RAM consumption...

Disable parallel daemon workers to save RAM during compilation

org.gradle.parallel=false
org.gradle.daemon=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
